imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: { enabled: true }
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/app/Resources/templates': templates
        '%kernel.project_dir%/src/Jon/BlogBundle': blog

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
            address: "matafestinfo@gmail.com"
            sender_name: "No Reply"

easy_admin:
    formats:
            date:     'Y'
            time:     'H:i'
            datetime: 'd/m/Y H:i:s'
    site_name: '<img src="/web/assets/img/logo.png" />MataFest'
    design:
            menu:
                - { entity: 'User', icon: 'user' }
                - { entity: 'Blog', icon: 'blog' }
                - { entity: 'Grupos', icon: 'guitar' }
            brand_color: '#050505'
#            color_scheme: 'light'

            assets:
                favicon: '/web/assets/img/favicon.png'
#                css:
#                    # HTTP protocol-relative URL
#                    - '//example.org/css/admin1.css'
#                    # absolute non-secure URL
#                    - 'http://example.org/css/admin2.css'
#                    # absolute secure URL
#                    - 'https://example.org/css/admin3.css'
#                    # absolute internal bundle URL
#                    - '/bundles/user/css/admin4.css'
#                    # relative internal bundle URL
#                    - 'bundles/app/css/admin5.css'
#                js:
#                    # this option works exactly the same as the 'css' option
#                    - '//example.org/js/admin1.js'
#                    - 'http://example.org/js/admin2.js'
#                    - 'https://example.org/js/admin3.js'
#                    - '/bundles/user/js/admin4.js'
#                    - 'bundles/app/js/admin5.js'
    entities:
        User:
            class: AppBundle\Entity\User
            list:
                fields: ['username', 'email', 'enabled']
            search:
                fields: ['username', 'email']
        Blog:
            class: Jon\BlogBundle\Entity\Blog
            list:
                fields: ['titulo', 'descripcion', { property: 'image', template: 'vich_uploader_image.html.twig' }, 'fecha', 'active']
            search:
                fields: ['titulo', 'descripcion', 'fecha']
            form:
                fields: ['titulo', { property: 'descripcion', type: 'ckeditor' }, { property: 'imageFile', type: 'vich_image' }, 'fecha', 'active']
        Grupos:
            class: Jon\BlogBundle\Entity\Grupos
            list:
                fields: ['nombre', { property: 'image', type: 'image', template: 'vich_uploader_image.html.twig' }, { property: 'anyo', label: 'Año' }, 'active']
            search:
                fields: ['nombre', 'anyo']
            form:
                fields: ['nombre', { property: 'descripcion', type: 'ckeditor' }, { property: 'imageFile', type: 'vich_image' }, { property: 'anyo', label: 'Año', format: 'Y' }, 'active']

vich_uploader:
    db_driver: orm
    mappings:
            grupos_images:
                uri_prefix:         '%app.path.grupos_images%'
                upload_destination: '%kernel.root_dir%/../web/assets/img/grupos'
            blog_images:
                uri_prefix:         '%app.path.blog_images%'
                upload_destination: '%kernel.root_dir%/../web/assets/img/blog'

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template